get_requirements Namespace Reference
This module contains all of the functionality that is needed to process the degree requirements.
Functions
get_all_tables (bs soup)
Finds all of the tables in the page gathered with BS4.
list get_table_rows (table)
Given a table, returns all its rows.
process_url (str url)
Take a url and find all of the tables contained in the page and return a ResultSet.
read_requirements (str url)
Read the requirements from a given url that contains degree requirements and process it into a dictionary.
dict compile_requirements (list[dict] requirements)
Gather multiple requirements sets and complile them so that the group names are unique.
None process_degree_requirements (list[str] urls, str json_file)
Handle the processing of multiple degree requirements and sending it to a json file.
Variables
current_directory = os.path.dirname(os.path.realpath(__file__))
path = current_directory.split(os.sep)
root_index = path.index('Capstone-Team14')
root_dir = os.sep.join(path[:root_index+1])
data_dir = os.path.join(root_dir, 'data_files', 'four_year_plan')
json_file = os.path.join(data_dir,'requirements.json')
list urls
Detailed Description
This module contains all of the functionality that is needed to process the degree requirements.
For proof of concept, running this package as a script utilizes the degree requirments from all five Computer Science Concentrations.
Function Documentation
compile_requirements()
 dict get_requirements.compile_requirements (list[dict] requirements)
Gather multiple requirements sets and complile them so that the group names are unique.
Parameters
requirements A list containing dictionaries that are structured with classes in groups and sub-groups
Returns
A single dictionary that combines all of the requirements into one while handling duplicate group labels by combining the class lists.
Referenced by process_degree_requirements().
get_all_tables()
get_requirements.get_all_tables (bs soup)
Finds all of the tables in the page gathered with BS4.
Parameters
 in soup The BeautifulSoup4 representation of the web page
Returns
A set containing all of the instances of <table></table> along with all of its contents
Referenced by process_url().
get_table_rows()
 list get_requirements.get_table_rows (table)
Given a table, returns all its rows.
Parameters
 in table A table from web page grabbed using BS4 soup object
Returns
A 2d list that represents all of the rows from the table
Referenced by process_url().
process_degree_requirements()
 None get_requirements.process_degree_requirements (list[str] urls, str json_file)
Handle the processing of multiple degree requirements and sending it to a json file.
Parameters
urls A list of url strings. Each url must direct to a page that contains requirements for some sort of degree
json_file A string that contains the file path and filename that the JSON will be written to.
NOTE to maintain the script's OS agnostic nature, it is suggested to utilize os.path.join() to join strings or os.sep.join() to join elements of a list
References compile_requirements(), and read_requirements().
process_url()
get_requirements.process_url (str url)
Take a url and find all of the tables contained in the page and return a ResultSet.
Parameters
url URL of the page to be searched.
Returns
List containing all of the tables in the page. Each of table is a 2d array (list)
References get_all_tables(), and get_table_rows().
Referenced by read_requirements().
read_requirements()
get_requirements.read_requirements (str url)
Read the requirements from a given url that contains degree requirements and process it into a dictionary.
Parameters
url A string that contains the url that is to be read to find the degree requirements
Returns
a dictionary that is structured to associate courses with the major and sub groups of requirements that are fulfilled
References process_url().
Referenced by process_degree_requirements().
Variable Documentation
current_directory
get_requirements.current_directory = os.path.dirname(os.path.realpath(__file__))
data_dir
get_requirements.data_dir = os.path.join(root_dir, 'data_files', 'four_year_plan')
json_file
get_requirements.json_file = os.path.join(data_dir,'requirements.json')
path
get_requirements.path = current_directory.split(os.sep)
root_dir
get_requirements.root_dir = os.sep.join(path[:root_index+1])
root_index
get_requirements.root_index = path.index('Capstone-Team14')
urls
list get_requirements.urls
Initial value:
= [
        'https://catalog.unomaha.edu/undergraduate/college-information-science-technology/computer-science/computer-science-bs/artificialintelligence-concentraton/',
        'https://catalog.unomaha.edu/undergraduate/college-information-science-technology/computer-science/computer-science-bs/game-programming-concentration/',
        'https://catalog.unomaha.edu/undergraduate/college-information-science-technology/computer-science/computer-science-bs/internet-technologies-it-concentration-computer-science-majors/',
        'https://catalog.unomaha.edu/undergraduate/college-information-science-technology/computer-science/computer-science-bs/information-assurance-concentration/',
        'https://catalog.unomaha.edu/undergraduate/college-information-science-technology/computer-science/computer-science-bs/software-engineering-concentration/'
    ]