process_constraints Namespace Reference
This module contains all of the functionality that is needed to convert the four year plan into usable clingo rules.
Functions
list[dict] get_plan (str filename)
Read the four year plan from a file and confirm that it is a list.
list get_semester (list[dict] plan, str|int year, str semester)
Get the list of classes for a particular semester from the four year plan, assuming that there may be multiple plans given.
dict set_contsraints (list semester_plan, int semester_id)
Process the semester such that classes listed as fulfilling the same requirement are soft constraints and all other classes in the semester are hard constraints.
dict combine_constraints (list[dict] constraints)
Combine the constraints so that the keys are based on the course and not based on the semester.
dict create_constraints (str filename)
Take a four year plan stored in a JSON file and process it so that it can be stored as JSON or as clingo in the desired format.
None convert_asp (dict constraints, str file)
Take formated constraints and convert it into asp rules In addition to the rules defined by the constraints parameter, the rules file is also appended with equivalence rules.
Variables
current_directory = os.path.dirname(os.path.realpath(__file__))
path = current_directory.split(os.sep)
root_index = path.index('Capstone-Team14')
root_dir = os.sep.join(path[:root_index+1])
data_dir = os.path.join(root_dir, 'data_files', 'four_year_plan')
filename = os.path.join(data_dir, 'fourYearPlan.json')
dict constraints = create_constraints(filename)
json_file = os.path.join(data_dir, 'constraints.json')
asp_file = os.path.join(data_dir, 'four_year_plan_constraints.lp')
f
indent
Detailed Description
This module contains all of the functionality that is needed to convert the four year plan into usable clingo rules.
For proof of concept running this package as a script utilizes the Computer Science four year plan.
Function Documentation
combine_constraints()
 dict process_constraints.combine_constraints (list[dict] constraints)
Combine the constraints so that the keys are based on the course and not based on the semester.
Parameters
constraints A list where each item in the list represents the classes in a semester
Returns
A dictionary whose keys are all of the classes described in the four year plan
Referenced by create_constraints().
convert_asp()
 None process_constraints.convert_asp (dict constraints, str file)
Take formated constraints and convert it into asp rules In addition to the rules defined by the constraints parameter, the rules file is also appended with equivalence rules.
$ a \equiv c \Leftarrow a \equiv b, b \equiv c $ $ b \in S \Leftarrow a \in S, a \equiv b $
etc.
Parameters
constraints
file A string that contains the file path and filename that the JSON will be written to.
NOTE to maintain the script's OS agnostic nature, it is suggested to utilize os.path.join() to join strings or os.sep.join() to join elements of a list
create_constraints()
 dict process_constraints.create_constraints (str filename)
Take a four year plan stored in a JSON file and process it so that it can be stored as JSON or as clingo in the desired format.
Parameters
filename A string that contains the file path and filename that the JSON will be written to.
NOTE to maintain the script's OS agnostic nature, it is suggested to utilize os.path.join() to join strings or os.sep.join() to join elements of a list
Returns
A dictionary whose keys are all of the courses in the four year plan
References combine_constraints(), get_plan(), get_semester(), and set_contsraints().
get_plan()
 list[dict] process_constraints.get_plan (str filename)
Read the four year plan from a file and confirm that it is a list.
Parameters
filename A string that contains the file path and filename that the JSON will be written to.
NOTE to maintain the script's OS agnostic nature, it is suggested to utilize os.path.join() to join strings or os.sep.join() to join elements of a list
Returns
The list of dictionaries that was read from the file.
Referenced by create_constraints().
get_semester()
 list process_constraints.get_semester (list[dict] plan, str|int year, str semester)
Get the list of classes for a particular semester from the four year plan, assuming that there may be multiple plans given.
Parameters
plan A list of dictionaries. Each dictionary defines a four year plan such that it has this structure
{ 'year':{ 'semsester':[ [ list of class numbers], [ list of class names], number of credits filled by the class(es) in the list ] ... } ...
 }
Parameters
year A string or an integer to identify the year in the plan that is to be read from. Options: ['First Year', 'Second Year', 'Third Year', 'Fourth Year'] or [1, 2, 3, 4]
Parameters
semester A string that determines if fall semester or spring semester Options: ['FALL', 'SPRING'] or any variation in capitalization
Returns
A list of classes in the same structure as origional semester list combined for all plans in the origional list.
Referenced by create_constraints().
set_contsraints()
 dict process_constraints.set_contsraints (list semester_plan, int semester_id)
Process the semester such that classes listed as fulfilling the same requirement are soft constraints and all other classes in the semester are hard constraints.
Parameters
semester_plan list of classes in the same semester in the same structure as the origional four year plan
Returns
Dictionary containing all of the classes in the semester Structure: <course number like csci2040>: { 'equivalent_courses': set, 'same_semester': set, 'credits': int, 'semsesters': set } ...
Referenced by create_constraints().
Variable Documentation
asp_file
process_constraints.asp_file = os.path.join(data_dir, 'four_year_plan_constraints.lp')
constraints
process_constraints.constraints = create_constraints(filename)
current_directory
process_constraints.current_directory = os.path.dirname(os.path.realpath(__file__))
data_dir
process_constraints.data_dir = os.path.join(root_dir, 'data_files', 'four_year_plan')
f
process_constraints.f
filename
process_constraints.filename = os.path.join(data_dir, 'fourYearPlan.json')
indent
process_constraints.indent
json_file
process_constraints.json_file = os.path.join(data_dir, 'constraints.json')
path
process_constraints.path = current_directory.split(os.sep)
root_dir
process_constraints.root_dir = os.sep.join(path[:root_index+1])
root_index
process_constraints.root_index = path.index('Capstone-Team14')