get_four_year Namespace Reference
This module contains all of the functionality that is needed to process the four year plan that is given with some url.
Functions
get_all_tables (bs soup)
Finds all of the tables in the page gathered with BS4.
list get_table_rows (table)
Given a table, returns all its rows.
process_url (str url)
Take a url and find all of the tables contained in the page and return a ResultSet.
read_four_year (url, output_file)
From a url that contains a four year plan process it and produce a JSON file in a structure that we can utilize to then convert into a clingo file.
Variables
current_directory = os.path.dirname(os.path.realpath(__file__))
path = current_directory.split(os.sep)
root_index = path.index('Capstone-Team14')
root_dir = os.sep.join(path[:root_index+1])
data_dir = os.path.join(root_dir, 'data_files', 'four_year_plan')
filename = os.path.join(data_dir,'fourYearPlan.json')
str url = 'https://catalog.unomaha.edu/undergraduate/college-information-science-technology/computer-science/computer-science-bs/#fouryearplantext'
Detailed Description
This module contains all of the functionality that is needed to process the four year plan that is given with some url.
For proof of concept running this package as a script utilizes the Computer Science four year plan.
Function Documentation
get_all_tables()
get_four_year.get_all_tables (bs soup)
Finds all of the tables in the page gathered with BS4.
Parameters
 in soup The BeautifulSoup4 representation of the web page
Returns
A set containing all of the instances of <table></table> along with all of its contents
Referenced by process_url().
get_table_rows()
 list get_four_year.get_table_rows (table)
Given a table, returns all its rows.
Parameters
 in table A table from web page grabbed using BS4 soup object
Returns
A 2d list that represents all of the rows from the table
Referenced by process_url().
process_url()
get_four_year.process_url (str url)
Take a url and find all of the tables contained in the page and return a ResultSet.
Parameters
url URL of the page to be searched.
Returns
List containing all of the tables in the page. Each of table is a 2d array (list)
References get_all_tables(), and get_table_rows().
Referenced by read_four_year().
read_four_year()
get_four_year.read_four_year (url, output_file)
From a url that contains a four year plan process it and produce a JSON file in a structure that we can utilize to then convert into a clingo file.
For the page in the computer science four year plan, create a JSON file with the class content organized by year and semester. This data is then used to discover conflicts that are higher priority.
@params url A string containing the url for the page with the four year plan @params output_file A string that contains the file path and filename that the JSON will be written to.
NOTE to maintain the script's OS agnostic nature, it is suggested to utilize os.path.join() to join strings or os.sep.join() to join elements of a list
References process_url().
Variable Documentation
current_directory
get_four_year.current_directory = os.path.dirname(os.path.realpath(__file__))
data_dir
get_four_year.data_dir = os.path.join(root_dir, 'data_files', 'four_year_plan')
filename
get_four_year.filename = os.path.join(data_dir,'fourYearPlan.json')
path
get_four_year.path = current_directory.split(os.sep)
root_dir
get_four_year.root_dir = os.sep.join(path[:root_index+1])
root_index
get_four_year.root_index = path.index('Capstone-Team14')
url
str get_four_year.url = 'https://catalog.unomaha.edu/undergraduate/college-information-science-technology/computer-science/computer-science-bs/#fouryearplantext'