clingo_pytest Namespace Reference
Functions
run_clingo (program_files)
parse_answer_set (output)
test_clingo_output (input_files, expected_output)
Function Documentation
parse_answer_set()
clingo_pytest.parse_answer_set (output)
Referenced by test_clingo_output().
run_clingo()
clingo_pytest.run_clingo (program_files)
Referenced by test_clingo_output().
test_clingo_output()
clingo_pytest.test_clingo_output (input_files, expected_output)
References parse_answer_set(), and run_clingo().