.TH "myproject Directory Reference" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myproject Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBasgi\&.py\fP"
.br
.ti -1c
.RI "file \fBsettings\&.py\fP"
.br
.ti -1c
.RI "file \fBurls\&.py\fP"
.br
.ti -1c
.RI "file \fBwsgi\&.py\fP"
.br
.in -1c
