.TH "scheduleFunctions/views Directory Reference" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions/views Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBclear_view\&.py\fP"
.br
.ti -1c
.RI "file \fBclingo_helpers\&.py\fP"
.br
.ti -1c
.RI "file \fBdashboard_view\&.py\fP"
.br
.ti -1c
.RI "file \fBdownload_optimized_file\&.py\fP"
.br
.ti -1c
.RI "file \fBlogin\&.py\fP"
.br
.ti -1c
.RI "file \fBoptimize_schedule\&.py\fP"
.br
.ti -1c
.RI "file \fBrun_clingo_identifier\&.py\fP"
.br
.ti -1c
.RI "file \fBsection_view\&.py\fP"
.br
.ti -1c
.RI "file \fBupload_json_file\&.py\fP"
.br
.in -1c
