.TH "clingo_pytest" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clingo_pytest
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBrun_clingo\fP (program_files)"
.br
.ti -1c
.RI "\fBparse_answer_set\fP (output)"
.br
.ti -1c
.RI "\fBtest_clingo_output\fP (input_files, expected_output)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "clingo_pytest\&.parse_answer_set ( output)"

.PP
Definition at line \fB37\fP of file \fBclingo_pytest\&.py\fP\&.
.SS "clingo_pytest\&.run_clingo ( program_files)"

.PP
Definition at line \fB30\fP of file \fBclingo_pytest\&.py\fP\&.
.SS "clingo_pytest\&.test_clingo_output ( input_files,  expected_output)"

.PP
Definition at line \fB72\fP of file \fBclingo_pytest\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
