.TH "scheduleFunctions/views/clingo_helpers.py" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions/views/clingo_helpers.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscheduleFunctions\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.views\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.views\&.clingo_helpers\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.clingo_helpers\&.get_root_path\fP ()"
.br
.RI "Returns the root path of the project by finding the 'Capstone-Team14' directory in the path\&. "
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.clingo_helpers\&.load_optimized_json\fP (path)"
.br
.RI "Loads and parses a JSON file from the specified path\&. "
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.clingo_helpers\&.convert_time\fP (t)"
.br
.RI "Converts a time in minutes to a human-readable 12-hour clock format with AM/PM\&. "
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.clingo_helpers\&.parse_line\fP (line)"
.br
.RI "Parses a single line of ASP output representing a scheduled section\&. "
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.clingo_helpers\&.convert_to_json\fP (symbols, output_file)"
.br
.RI "Converts a list of ASP symbols to a structured JSON file\&. "
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.clingo_helpers\&.run_clingo_optimization\fP (asp_filename, asp_solver)"
.br
.RI "Runs Clingo on the given ASP program and minimizer, using all available threads\&. "
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.clingo_helpers\&.save_optimized_file\fP (data, filename)"
.br
.RI "Saves a Python dictionary as a formatted JSON file using Django's storage system\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
