.TH "scheduleFunctions/data_processing/convert_four_year.py" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions/data_processing/convert_four_year.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscheduleFunctions\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.data_processing\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.data_processing\&.convert_four_year\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscheduleFunctions\&.data_processing\&.convert_four_year\&.four_year_to_clingo\fP (\fBjson_file\fP, \fBoutput_file\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBscheduleFunctions\&.data_processing\&.convert_four_year\&.json_file\fP = r'C:\\Users\\Josh\\Documents\\GitHub\\Capstone\-Team14\\data_files\\four_year_plan\\fourYearPlan\&.json'"
.br
.ti -1c
.RI "str \fBscheduleFunctions\&.data_processing\&.convert_four_year\&.output_file\fP = json_file\&.replace('\&.json', '\&.lp')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
