.TH "get_test_case" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_test_case
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "dict \fBget_classes\fP (str filename)"
.br
.ti -1c
.RI "dict \fBcreate_sample\fP (dict \fBclasses\fP, int num_semesters, int num_departments, int num_classes)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcurrent_directory\fP = os\&.path\&.dirname(os\&.path\&.realpath(__file__))"
.br
.ti -1c
.RI "\fBtest_folder_dir\fP = os\&.path\&.split(\fBcurrent_directory\fP)[0]"
.br
.ti -1c
.RI "\fBtest_cases_dir\fP = os\&.path\&.join(\fBtest_folder_dir\fP,'test_cases')"
.br
.ti -1c
.RI "dict \fBclasses\fP = \fBget_classes\fP('filtered\&.json')"
.br
.ti -1c
.RI "dict \fBsample_data\fP = \fBcreate_sample\fP(\fBclasses\fP, 1, 2, 5)"
.br
.ti -1c
.RI "\fBf\fP"
.br
.ti -1c
.RI "\fBindent\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " dict get_test_case\&.create_sample (dict classes, int num_semesters, int num_departments, int num_classes)"

.PP
Definition at line \fB22\fP of file \fBget_test_case\&.py\fP\&.
.SS " dict get_test_case\&.get_classes (str filename)"

.PP
Definition at line \fB14\fP of file \fBget_test_case\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "dict get_test_case\&.classes = \fBget_classes\fP('filtered\&.json')"

.PP
Definition at line \fB49\fP of file \fBget_test_case\&.py\fP\&.
.SS "get_test_case\&.current_directory = os\&.path\&.dirname(os\&.path\&.realpath(__file__))"

.PP
Definition at line \fB6\fP of file \fBget_test_case\&.py\fP\&.
.SS "get_test_case\&.f"

.PP
Definition at line \fB55\fP of file \fBget_test_case\&.py\fP\&.
.SS "get_test_case\&.indent"

.PP
Definition at line \fB55\fP of file \fBget_test_case\&.py\fP\&.
.SS "get_test_case\&.sample_data = \fBcreate_sample\fP(\fBclasses\fP, 1, 2, 5)"

.PP
Definition at line \fB52\fP of file \fBget_test_case\&.py\fP\&.
.SS "get_test_case\&.test_cases_dir = os\&.path\&.join(\fBtest_folder_dir\fP,'test_cases')"

.PP
Definition at line \fB43\fP of file \fBget_test_case\&.py\fP\&.
.SS "get_test_case\&.test_folder_dir = os\&.path\&.split(\fBcurrent_directory\fP)[0]"

.PP
Definition at line \fB12\fP of file \fBget_test_case\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
