.TH "identifier.py" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
identifier.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBidentifier\&.ClingoApp\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBidentifier\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBidentifier\&.current_directory\fP"
.br
.ti -1c
.RI "\fBidentifier\&.path\fP = current_directory\&.split(os\&.sep)"
.br
.ti -1c
.RI "\fBidentifier\&.root_index\fP = path\&.index('Capstone\-Team14')"
.br
.ti -1c
.RI "\fBidentifier\&.root_dir\fP = os\&.sep\&.join(\fBpath\fP[: \fBroot_index\fP + 1])"
.br
.ti -1c
.RI "\fBidentifier\&.read_dir\fP = os\&.path\&.join(\fBroot_dir\fP, 'media', 'uploads')"
.br
.ti -1c
.RI "\fBidentifier\&.clingo_dir\fP = os\&.path\&.join(\fBroot_dir\fP, 'clingo')"
.br
.ti -1c
.RI "\fBidentifier\&.parser\fP = argparse\&.ArgumentParser(description='Input class json')"
.br
.ti -1c
.RI "\fBidentifier\&.type\fP"
.br
.ti -1c
.RI "\fBidentifier\&.default\fP"
.br
.ti -1c
.RI "\fBidentifier\&.help\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
