.TH "identifier.ClingoApp" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
identifier.ClingoApp
.SH SYNOPSIS
.br
.PP
.PP
Inherits clingo\&.application\&.Application\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP (self, ctl, files)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB33\fP of file \fBidentifier\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "identifier\&.ClingoApp\&.main ( self,  ctl,  files)"

.PP
Definition at line \fB34\fP of file \fBidentifier\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
