.TH "jsonconverter" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsonconverter
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBconvert24\fP (time)"
.br
.ti -1c
.RI "\fBconvert\fP (str file)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "jsonconverter\&.convert (str file)"

.PP
Definition at line \fB11\fP of file \fBjsonconverter\&.py\fP\&.
.SS "jsonconverter\&.convert24 ( time)"

.PP
Definition at line \fB6\fP of file \fBjsonconverter\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
