.TH "scheduleFunctions/data_processing/jsonconverter.py" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions/data_processing/jsonconverter.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscheduleFunctions\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.data_processing\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.data_processing\&.jsonconverter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscheduleFunctions\&.data_processing\&.jsonconverter\&.convert24\fP (time)"
.br
.ti -1c
.RI "\fBscheduleFunctions\&.data_processing\&.jsonconverter\&.convert\fP (str \fBfile\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBscheduleFunctions\&.data_processing\&.jsonconverter\&.file\fP = r'C:\\Users\\cjgry\\Documents\\Capstone\\Capstone\-Team14\\media\\fa21\-fa24\&.json'"
.br
.ti -1c
.RI "\fBscheduleFunctions\&.data_processing\&.jsonconverter\&.facts\fP = \fBconvert\fP(\fBfile\fP)"
.br
.ti -1c
.RI "str \fBscheduleFunctions\&.data_processing\&.jsonconverter\&.asp_filename\fP = file\&.replace('\&.json', '\&.lp')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
