.TH "manage" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
manage
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Django's command-line utility for administrative tasks\&.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "manage\&.main ()"

.PP
.nf
Run administrative tasks\&.
.fi
.PP
 
.PP
Definition at line \fB7\fP of file \fBmanage\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
