.TH "scheduleFunctions/models.py" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions/models.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Room\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Day\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Course\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Course\&.Meta\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Requirement\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Proffessor\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.TimeSlot\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Section\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.PlanSemester\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.FilteredUpload\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscheduleFunctions\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
