.TH "scheduleFunctions/views/run_clingo_identifier.py" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions/views/run_clingo_identifier.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscheduleFunctions\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.views\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.views\&.run_clingo_identifier\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.run_clingo_identifier\&.run_clingo_identifier\fP (request)"
.br
.RI "Run the clingo program for identifying conflict\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
