.TH "scheduleFunctions.models" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCourse\fP"
.br
.ti -1c
.RI "class \fBDay\fP"
.br
.ti -1c
.RI "class \fBFilteredUpload\fP"
.br
.ti -1c
.RI "class \fBPlanSemester\fP"
.br
.ti -1c
.RI "class \fBProffessor\fP"
.br
.ti -1c
.RI "class \fBRequirement\fP"
.br
.ti -1c
.RI "class \fBRoom\fP"
.br
.ti -1c
.RI "class \fBSection\fP"
.br
.ti -1c
.RI "class \fBTimeSlot\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
