.TH "scheduleFunctions.data_processing" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.data_processing
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBconvert_four_year\fP"
.br
.ti -1c
.RI "namespace \fBconverter\fP"
.br
.ti -1c
.RI "namespace \fBdescription\fP"
.br
.ti -1c
.RI "namespace \fBget_four_year\fP"
.br
.ti -1c
.RI "namespace \fBget_requirements\fP"
.br
.ti -1c
.RI "namespace \fBget_sample\fP"
.br
.ti -1c
.RI "namespace \fBjsonconverter\fP"
.br
.ti -1c
.RI "namespace \fBoptimizer\fP"
.br
.ti -1c
.RI "namespace \fBprocess_four_year\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
