.TH "scheduleFunctions.models.TimeSlot" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.models.TimeSlot
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "str \fBprint_clingo\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstart_time\fP = models\&.TimeField(auto_now=False)"
.br
.ti -1c
.RI "\fBend_time\fP = models\&.TimeField(auto_now=False)"
.br
.ti -1c
.RI "\fBdays\fP = models\&.ManyToManyField(\fBDay\fP)"
.br
.ti -1c
.RI "\fBcredits\fP = models\&.IntegerField()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB117\fP of file \fBmodels\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " str scheduleFunctions\&.models\&.TimeSlot\&.print_clingo ( self)"

.PP
Definition at line \fB123\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "scheduleFunctions\&.models\&.TimeSlot\&.credits = models\&.IntegerField()\fR [static]\fP"

.PP
Definition at line \fB121\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.TimeSlot\&.days = models\&.ManyToManyField(\fBDay\fP)\fR [static]\fP"

.PP
Definition at line \fB120\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.TimeSlot\&.end_time = models\&.TimeField(auto_now=False)\fR [static]\fP"

.PP
Definition at line \fB119\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.TimeSlot\&.start_time = models\&.TimeField(auto_now=False)\fR [static]\fP"

.PP
Definition at line \fB118\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
