.TH "scheduleFunctions.views.clear_view" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.views.clear_view
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBclear_view\fP (request)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "scheduleFunctions\&.views\&.clear_view\&.clear_view ( request)"

.PP
Definition at line \fB6\fP of file \fBclear_view\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
