.TH "scheduleFunctions.data_processing.convert_four_year" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.data_processing.convert_four_year
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfour_year_to_clingo\fP (\fBjson_file\fP, \fBoutput_file\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBjson_file\fP = r'C:\\Users\\Josh\\Documents\\GitHub\\Capstone\-Team14\\data_files\\four_year_plan\\fourYearPlan\&.json'"
.br
.ti -1c
.RI "str \fBoutput_file\fP = json_file\&.replace('\&.json', '\&.lp')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "scheduleFunctions\&.data_processing\&.convert_four_year\&.four_year_to_clingo ( json_file,  output_file)"

.PP
Definition at line \fB4\fP of file \fBconvert_four_year\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "str scheduleFunctions\&.data_processing\&.convert_four_year\&.json_file = r'C:\\Users\\Josh\\Documents\\GitHub\\Capstone\-Team14\\data_files\\four_year_plan\\fourYearPlan\&.json'"

.PP
Definition at line \fB48\fP of file \fBconvert_four_year\&.py\fP\&.
.SS "str scheduleFunctions\&.data_processing\&.convert_four_year\&.output_file = json_file\&.replace('\&.json', '\&.lp')"

.PP
Definition at line \fB49\fP of file \fBconvert_four_year\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
