.TH "scheduleFunctions.to_database" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.to_database
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstore_requirements\fP (json_file)"
.br
.ti -1c
.RI "None \fBstore_plan\fP (json_file)"
.br
.ti -1c
.RI "None \fBstore_schedule\fP (str json_file)"
.br
.ti -1c
.RI "None \fBstore_schedule_changes\fP (int section_id, date start_time, date end_time, str days)"
.br
.ti -1c
.RI "\fBclear_schedule\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "scheduleFunctions\&.to_database\&.clear_schedule ()"

.PP
Definition at line \fB322\fP of file \fBto_database\&.py\fP\&.
.SS " None scheduleFunctions\&.to_database\&.store_plan ( json_file)"

.PP
Definition at line \fB52\fP of file \fBto_database\&.py\fP\&.
.SS "scheduleFunctions\&.to_database\&.store_requirements ( json_file)"

.PP
Definition at line \fB9\fP of file \fBto_database\&.py\fP\&.
.SS " None scheduleFunctions\&.to_database\&.store_schedule (str json_file)"

.PP
Definition at line \fB146\fP of file \fBto_database\&.py\fP\&.
.SS " None scheduleFunctions\&.to_database\&.store_schedule_changes (int section_id, date start_time, date end_time, str days)"

.PP
Definition at line \fB282\fP of file \fBto_database\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
