.TH "scheduleFunctions.apps.SchedulefunctionsConfig" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.apps.SchedulefunctionsConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits AppConfig\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBready\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBdefault_auto_field\fP = 'django\&.db\&.models\&.BigAutoField'"
.br
.ti -1c
.RI "str \fBname\fP = 'scheduleFunctions'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBapps\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "scheduleFunctions\&.apps\&.SchedulefunctionsConfig\&.ready ( self)"

.PP
Definition at line \fB12\fP of file \fBapps\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str scheduleFunctions\&.apps\&.SchedulefunctionsConfig\&.default_auto_field = 'django\&.db\&.models\&.BigAutoField'\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBapps\&.py\fP\&.
.SS "str scheduleFunctions\&.apps\&.SchedulefunctionsConfig\&.name = 'scheduleFunctions'\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBapps\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
