.TH "scheduleFunctions.data_processing.jsonconverter" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.data_processing.jsonconverter
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBconvert24\fP (time)"
.br
.ti -1c
.RI "\fBconvert\fP (str \fBfile\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBfile\fP = r'C:\\Users\\cjgry\\Documents\\Capstone\\Capstone\-Team14\\media\\fa21\-fa24\&.json'"
.br
.ti -1c
.RI "\fBfacts\fP = \fBconvert\fP(\fBfile\fP)"
.br
.ti -1c
.RI "str \fBasp_filename\fP = file\&.replace('\&.json', '\&.lp')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "scheduleFunctions\&.data_processing\&.jsonconverter\&.convert (str file)"

.PP
Definition at line \fB11\fP of file \fBjsonconverter\&.py\fP\&.
.SS "scheduleFunctions\&.data_processing\&.jsonconverter\&.convert24 ( time)"

.PP
Definition at line \fB6\fP of file \fBjsonconverter\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "str scheduleFunctions\&.data_processing\&.jsonconverter\&.asp_filename = file\&.replace('\&.json', '\&.lp')"

.PP
Definition at line \fB150\fP of file \fBjsonconverter\&.py\fP\&.
.SS "scheduleFunctions\&.data_processing\&.jsonconverter\&.facts = \fBconvert\fP(\fBfile\fP)"

.PP
Definition at line \fB147\fP of file \fBjsonconverter\&.py\fP\&.
.SS "str scheduleFunctions\&.data_processing\&.jsonconverter\&.file = r'C:\\Users\\cjgry\\Documents\\Capstone\\Capstone\-Team14\\media\\fa21\-fa24\&.json'"

.PP
Definition at line \fB146\fP of file \fBjsonconverter\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
