.TH "scheduleFunctions.models.Room" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.models.Room
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "str \fBprint_clingo\fP (self)"
.br
.ti -1c
.RI "\fBprint_all_clingo\fP (cls)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBbuilding\fP = models\&.CharField(max_length=255)"
.br
.ti -1c
.RI "\fBroom_number\fP = models\&.IntegerField()"
.br
.ti -1c
.RI "\fBcapacity\fP = models\&.IntegerField(default=30)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBmodels\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "scheduleFunctions\&.models\&.Room\&.print_all_clingo ( cls)"

.PP
Definition at line \fB17\fP of file \fBmodels\&.py\fP\&.
.SS " str scheduleFunctions\&.models\&.Room\&.print_clingo ( self)"

.PP
Definition at line \fB9\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "scheduleFunctions\&.models\&.Room\&.building = models\&.CharField(max_length=255)\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Room\&.capacity = models\&.IntegerField(default=30)\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Room\&.room_number = models\&.IntegerField()\fR [static]\fP"

.PP
Definition at line \fB6\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
