.TH "scheduleFunctions.models.Course.Meta" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.models.Course.Meta
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBconstraints\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB81\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "list scheduleFunctions\&.models\&.Course\&.Meta\&.constraints\fR [static]\fP"
\fBInitial value:\fP
.nf
=  [
            models\&.UniqueConstraint(fields=['subject', 'class_number'], name='unique_course_code')
        ]
.PP
.fi

.PP
Definition at line \fB82\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
