.TH "myproject/settings.py" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myproject/settings.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmyproject\fP"
.br
.ti -1c
.RI "namespace \fBmyproject\&.settings\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmyproject\&.settings\&.BASE_DIR\fP = Path(__file__)\&.resolve()\&.parent\&.parent"
.br
.ti -1c
.RI "str \fBmyproject\&.settings\&.SECRET_KEY\fP = 'django\-insecure\-ge_nw#14sw5!gaz+x\-ydw2n0*qf(6t(m3!_linr*45iyv_dqim'"
.br
.ti -1c
.RI "bool \fBmyproject\&.settings\&.DEBUG\fP = True"
.br
.ti -1c
.RI "list \fBmyproject\&.settings\&.ALLOWED_HOSTS\fP = ['*']"
.br
.ti -1c
.RI "list \fBmyproject\&.settings\&.INSTALLED_APPS\fP"
.br
.ti -1c
.RI "list \fBmyproject\&.settings\&.MIDDLEWARE\fP"
.br
.ti -1c
.RI "str \fBmyproject\&.settings\&.ROOT_URLCONF\fP = 'myproject\&.urls'"
.br
.ti -1c
.RI "list \fBmyproject\&.settings\&.TEMPLATES\fP"
.br
.ti -1c
.RI "str \fBmyproject\&.settings\&.WSGI_APPLICATION\fP = '\fBmyproject\&.wsgi\&.application\fP'"
.br
.ti -1c
.RI "dict \fBmyproject\&.settings\&.DATABASES\fP"
.br
.ti -1c
.RI "list \fBmyproject\&.settings\&.AUTH_PASSWORD_VALIDATORS\fP"
.br
.ti -1c
.RI "str \fBmyproject\&.settings\&.LANGUAGE_CODE\fP = 'en\-us'"
.br
.ti -1c
.RI "str \fBmyproject\&.settings\&.TIME_ZONE\fP = 'UTC'"
.br
.ti -1c
.RI "bool \fBmyproject\&.settings\&.USE_I18N\fP = True"
.br
.ti -1c
.RI "bool \fBmyproject\&.settings\&.USE_TZ\fP = True"
.br
.ti -1c
.RI "str \fBmyproject\&.settings\&.STATIC_URL\fP = 'static/'"
.br
.ti -1c
.RI "str \fBmyproject\&.settings\&.DEFAULT_AUTO_FIELD\fP = 'django\&.db\&.models\&.BigAutoField'"
.br
.ti -1c
.RI "str \fBmyproject\&.settings\&.MEDIA_URL\fP = '/media/'"
.br
.ti -1c
.RI "\fBmyproject\&.settings\&.MEDIA_ROOT\fP = os\&.path\&.join(\fBBASE_DIR\fP, 'media')"
.br
.ti -1c
.RI "list \fBmyproject\&.settings\&.STATICFILES_DIRS\fP"
.br
.ti -1c
.RI "bool \fBmyproject\&.settings\&.STARTUP_DONE\fP = False"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
