.TH "scheduleFunctions/to_database.py" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions/to_database.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscheduleFunctions\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.to_database\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscheduleFunctions\&.to_database\&.store_requirements\fP (json_file)"
.br
.ti -1c
.RI "None \fBscheduleFunctions\&.to_database\&.store_plan\fP (json_file)"
.br
.ti -1c
.RI "None \fBscheduleFunctions\&.to_database\&.store_schedule\fP (str json_file)"
.br
.ti -1c
.RI "None \fBscheduleFunctions\&.to_database\&.store_schedule_changes\fP (int section_id, date start_time, date end_time, str days)"
.br
.ti -1c
.RI "\fBscheduleFunctions\&.to_database\&.clear_schedule\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
