.TH "scheduleFunctions/views/upload_json_file.py" 3 "Version 0.5" "Capstone Team 14" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions/views/upload_json_file.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscheduleFunctions\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.views\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.views\&.upload_json_file\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.upload_json_file\&.convert24\fP (time)"
.br
.RI "Converts a 12-hour formatted time string to minutes past midnight\&. "
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.upload_json_file\&.convert_json_to_lp\fP (schedule_list)"
.br
.RI "Converts a nested JSON schedule dictionary into ASP logic program facts\&. "
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.upload_json_file\&.upload_json_file\fP (request)"
.br
.RI "Handles uploading of a JSON file and its conversion to ASP logic facts\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBscheduleFunctions\&.views\&.upload_json_file\&.SUBJECTS_OF_INTEREST\fP = {'CIST', 'CSCI'}"
.br
.ti -1c
.RI "dict \fBscheduleFunctions\&.views\&.upload_json_file\&.NON_CS_SUBJECTS_OF_INTEREST\fP = {'ENGL', 'MATH', 'CMST'}"
.br
.ti -1c
.RI "dict \fBscheduleFunctions\&.views\&.upload_json_file\&.NON_CS_COURSES_OF_INTEREST\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Capstone Team 14 from the source code\&.
