# Generated by Django 5.1.6 on 2025-04-04 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('FRI', 'Friday')], default='Mon', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=255)),
                ('room_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('semester', models.CharField(choices=[('F', 'Fall'), ('S', 'Spring')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=5)),
                ('classNumber', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('equivalent_courses', models.ManyToManyField(to='scheduleFunctions.course')),
                ('prerequisites', models.ManyToManyField(to='scheduleFunctions.course')),
                ('same_semester_courses', models.ManyToManyField(to='scheduleFunctions.course')),
            ],
        ),
        migrations.CreateModel(
            name='PlanSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('semester', models.CharField(choices=[('F', 'Fall'), ('S', 'Spring')], default='F', max_length=1)),
                ('courses', models.ManyToManyField(to='scheduleFunctions.course')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_group_label', models.CharField(max_length=255)),
                ('group_label', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('courses', models.ManyToManyField(to='scheduleFunctions.course')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_start_time', models.IntegerField()),
                ('new_end_time', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleFunctions.course')),
                ('new_days', models.ManyToManyField(to='scheduleFunctions.day')),
                ('new_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleFunctions.room')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField()),
                ('professor', models.CharField(max_length=255)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleFunctions.course')),
                ('days', models.ManyToManyField(to='scheduleFunctions.day')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduleFunctions.room')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleFunctions.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.ManyToManyField(to='scheduleFunctions.section')),
            ]
        ),
        migrations.CreateModel(
            name='FilteredUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('filtered_data', models.JSONField()),
            ],
        ),
    ]
