# Generated by Django 5.1.6 on 2025-04-20 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('m', 'Monday'), ('t', 'Tuesday'), ('w', 'Wednesday'), ('r', 'Thursday'), ('f', 'Friday')], default='m', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='FilteredUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('filtered_data', models.JSONField()),
                ('non_filtered_data', models.JSONField()),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('raw_file_path', models.CharField(blank=True, max_length=255)),
                ('filtered_file_path', models.CharField(blank=True, max_length=255)),
                ('remaining_file_path', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=255)),
                ('room_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=5)),
                ('class_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('equivalent_courses', models.ManyToManyField(to='scheduleFunctions.course')),
                ('prerequisites', models.ManyToManyField(to='scheduleFunctions.course')),
                ('same_semester_courses', models.ManyToManyField(to='scheduleFunctions.course')),
            ],
        ),
        migrations.CreateModel(
            name='PlanSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('semester', models.CharField(choices=[('F', 'Fall'), ('S', 'Spring')], default='F', max_length=1)),
                ('courses', models.ManyToManyField(to='scheduleFunctions.course')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_label', models.CharField(max_length=255)),
                ('requirement_label', models.CharField(max_length=255)),
                ('total_credits', models.IntegerField()),
                ('course_options', models.ManyToManyField(to='scheduleFunctions.course')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_start_time', models.IntegerField()),
                ('new_end_time', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleFunctions.course')),
                ('new_days', models.ManyToManyField(to='scheduleFunctions.day')),
                ('new_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduleFunctions.room')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_number', models.IntegerField()),
                ('section_id', models.IntegerField(primary_key=True, serialize=False)),
                ('professor', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleFunctions.course')),
                ('days', models.ManyToManyField(to='scheduleFunctions.day')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduleFunctions.room')),
            ],
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_A', to='scheduleFunctions.section')),
                ('sectionB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_B', to='scheduleFunctions.section')),
            ],
        ),
    ]
