# Generated by Django 5.2 on 2025-04-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleFunctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteredupload',
            name='filtered_file_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filteredupload',
            name='raw_file_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filteredupload',
            name='remaining_file_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
