# Generated by Django 5.1.6 on 2025-03-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleFunctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteredupload',
            name='uploaded_file',
            field=models.FileField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
