# Generated by Django 5.1.6 on 2025-04-30 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleFunctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduleFunctions.proffessor'),
        ),
    ]
