# Generated by Django 5.1.6 on 2025-05-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleFunctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
