# Generated by Django 5.1.6 on 2025-04-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleFunctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(null=True),
        ),
    ]
