# Generated by Django 5.1.6 on 2025-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleFunctions', '0002_filteredupload_filtered_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteredupload',
            name='optimized_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
