# Generated by Django 5.1.6 on 2025-04-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleFunctions', '0002_alter_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=30),
        ),
    ]
