# Generated by Django 5.1.6 on 2025-04-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleFunctions', '0002_filteredupload_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classNumber',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='test0000', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.CharField(default='test0000', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
