.TH "data_processing Directory Reference" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_processing Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBget_four_year\&.py\fP"
.br
.ti -1c
.RI "file \fBget_requirements\&.py\fP"
.br
.ti -1c
.RI "file \fBprocess_constraints\&.py\fP"
.br
.in -1c
