.TH "testing/clingo_tests/clingo_pytest.py" 3 "Version 3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing/clingo_tests/clingo_pytest.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBclingo_pytest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBclingo_pytest\&.run_clingo\fP (program_files)"
.br
.ti -1c
.RI "\fBclingo_pytest\&.parse_answer_set\fP (output)"
.br
.ti -1c
.RI "\fBclingo_pytest\&.test_clingo_output\fP (input_files, expected_output)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
