.TH "converter.py" 3 "Version 3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
converter.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBconverter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBconverter\&.clean_course_name\fP (course)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBconverter\&.file_path\fP = 'filtered\&.json'"
.br
.ti -1c
.RI "\fBconverter\&.data\fP = json\&.load(file)"
.br
.ti -1c
.RI "dict \fBconverter\&.course_prereqs\fP = {}"
.br
.ti -1c
.RI "\fBconverter\&.strict_prereq_pattern\fP = re\&.compile(r'([\\w\\s]+) with C[\-]? or better|([\\w\\s]+) AND|([\\w\\s]+) OR')"
.br
.ti -1c
.RI "\fBconverter\&.title\fP = course_info\&.get('title', 'Unknown Title')"
.br
.ti -1c
.RI "\fBconverter\&.prereq_text\fP = course_info\&.get('desc', '')"
.br
.ti -1c
.RI "\fBconverter\&.prereq_part\fP = prereq_text\&.split('Prereq:')[1]\&.strip()"
.br
.ti -1c
.RI "\fBconverter\&.matches\fP = strict_prereq_pattern\&.findall(\fBprereq_part\fP)"
.br
.ti -1c
.RI "\fBconverter\&.all_prereqs\fP = set()"
.br
.ti -1c
.RI "str \fBconverter\&.structured_prereq\fP = f'choice([{', '\&.join(\fBall_prereqs\fP)}])'"
.br
.ti -1c
.RI "str \fBconverter\&.course_key\fP = f'{\fBclean_course_name\fP(subject)}_{course_number}'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
