.TH "description" 3 "Version 3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
description
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBfile_path\fP = 'filtered\&.json'"
.br
.ti -1c
.RI "\fBdata\fP = json\&.load(file)"
.br
.ti -1c
.RI "dict \fBcourse_prerequisites\fP = {}"
.br
.ti -1c
.RI "\fBtitle\fP = course_info\&.get('title', 'Unknown Title')"
.br
.ti -1c
.RI "\fBprereq_text\fP = course_info\&.get('desc', '')"
.br
.ti -1c
.RI "\fBprereq_part\fP = prereq_text\&.split('Prereq:')[1]\&.strip()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "dict description\&.course_prerequisites = {}"

.PP
Definition at line \fB9\fP of file \fBdescription\&.py\fP\&.
.SS "description\&.data = json\&.load(file)"

.PP
Definition at line \fB6\fP of file \fBdescription\&.py\fP\&.
.SS "str description\&.file_path = 'filtered\&.json'"

.PP
Definition at line \fB4\fP of file \fBdescription\&.py\fP\&.
.SS "description\&.prereq_part = prereq_text\&.split('Prereq:')[1]\&.strip()"

.PP
Definition at line \fB20\fP of file \fBdescription\&.py\fP\&.
.SS "description\&.prereq_text = course_info\&.get('desc', '')"

.PP
Definition at line \fB16\fP of file \fBdescription\&.py\fP\&.
.SS "description\&.title = course_info\&.get('title', 'Unknown Title')"

.PP
Definition at line \fB15\fP of file \fBdescription\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
