.TH "get_sample.py" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_sample.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBget_sample\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "dict \fBget_sample\&.get_classes\fP (str filename)"
.br
.ti -1c
.RI "dict \fBget_sample\&.create_sample\fP (dict \fBclasses\fP, int num_semesters, int num_departments, int num_classes)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBget_sample\&.classes\fP = \fBget_classes\fP('filtered\&.json')"
.br
.ti -1c
.RI "dict \fBget_sample\&.sample_data\fP = \fBcreate_sample\fP(\fBclasses\fP, 1, 2, 5)"
.br
.ti -1c
.RI "\fBget_sample\&.f\fP"
.br
.ti -1c
.RI "\fBget_sample\&.indent\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
