.TH "get_sample" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_sample
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "dict \fBget_classes\fP (str filename)"
.br
.ti -1c
.RI "dict \fBcreate_sample\fP (dict \fBclasses\fP, int num_semesters, int num_departments, int num_classes)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBclasses\fP = \fBget_classes\fP('filtered\&.json')"
.br
.ti -1c
.RI "dict \fBsample_data\fP = \fBcreate_sample\fP(\fBclasses\fP, 1, 2, 5)"
.br
.ti -1c
.RI "\fBf\fP"
.br
.ti -1c
.RI "\fBindent\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS " dict get_sample\&.create_sample (dict classes, int num_semesters, int num_departments, int num_classes)"

.PP
Definition at line \fB13\fP of file \fBget_sample\&.py\fP\&.
.nf
13 def create_sample(classes:dict, num_semesters:int, num_departments:int, num_classes:int) \-> dict:
14     sample_data = {}
15     key_list = list(classes\&.keys())
16     semester_subset = sample(key_list,min(num_semesters,len(key_list)))
17     for semester in semester_subset:
18         sample_data[semester] = {}
19         key_list = list(classes[semester]\&.keys())
20         department_subset = sample(key_list,min(num_departments,len(key_list)))
21         for department in department_subset:
22             key_list = list(classes[semester][department]\&.keys())
23             class_subset = sample(key_list,min(num_classes,len(key_list)))
24             class_list = {class_name: classes[semester][department][class_name] for class_name in class_subset}
25             print(class_list)
26             sample_data[semester][department] = class_list
27             
28     return sample_data
29 
.PP
.fi

.SS " dict get_sample\&.get_classes (str filename)"

.PP
Definition at line \fB5\fP of file \fBget_sample\&.py\fP\&.
.nf
5 def get_classes(filename: str) \-> dict:
6     classes = {}
7 
8     with open(filename, 'r') as f:
9         classes = json\&.load(f)
10         
11     return classes
12 
.PP
.fi

.SH "Variable Documentation"
.PP 
.SS "dict get_sample\&.classes = \fBget_classes\fP('filtered\&.json')"

.PP
Definition at line \fB35\fP of file \fBget_sample\&.py\fP\&.
.SS "get_sample\&.f"

.PP
Definition at line \fB42\fP of file \fBget_sample\&.py\fP\&.
.SS "get_sample\&.indent"

.PP
Definition at line \fB42\fP of file \fBget_sample\&.py\fP\&.
.SS "get_sample\&.sample_data = \fBcreate_sample\fP(\fBclasses\fP, 1, 2, 5)"

.PP
Definition at line \fB38\fP of file \fBget_sample\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
