.TH "data_processing/get_requirements.py" 3 "Version 3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_processing/get_requirements.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBget_requirements\fP"
.br
.RI "This module contains all of the functionality that is needed to process the degree requirements\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBget_requirements\&.get_all_tables\fP (bs soup)"
.br
.RI "Finds all of the tables in the page gathered with BS4\&. "
.ti -1c
.RI "list \fBget_requirements\&.get_table_rows\fP (table)"
.br
.RI "Given a table, returns all its rows\&. "
.ti -1c
.RI "\fBget_requirements\&.process_url\fP (str url)"
.br
.RI "Take a url and find all of the tables contained in the page and return a ResultSet\&. "
.ti -1c
.RI "\fBget_requirements\&.read_requirements\fP (str url)"
.br
.RI "Read the requirements from a given url that contains degree requirements and process it into a dictionary\&. "
.ti -1c
.RI "dict \fBget_requirements\&.compile_requirements\fP (list[dict] requirements)"
.br
.RI "Gather multiple requirements sets and complile them so that the group names are unique\&. "
.ti -1c
.RI "None \fBget_requirements\&.process_degree_requirements\fP (list[str] \fBurls\fP, str \fBjson_file\fP)"
.br
.RI "Handle the processing of multiple degree requirements and sending it to a json file\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBget_requirements\&.current_directory\fP = os\&.path\&.dirname(os\&.path\&.realpath(__file__))"
.br
.ti -1c
.RI "\fBget_requirements\&.path\fP = current_directory\&.split(os\&.sep)"
.br
.ti -1c
.RI "\fBget_requirements\&.root_index\fP = path\&.index('Capstone\-Team14')"
.br
.ti -1c
.RI "\fBget_requirements\&.root_dir\fP = os\&.sep\&.join(\fBpath\fP[:\fBroot_index\fP+1])"
.br
.ti -1c
.RI "\fBget_requirements\&.data_dir\fP = os\&.path\&.join(\fBroot_dir\fP, 'data_files', 'four_year_plan')"
.br
.ti -1c
.RI "\fBget_requirements\&.json_file\fP = os\&.path\&.join(\fBdata_dir\fP,'requirements\&.json')"
.br
.ti -1c
.RI "list \fBget_requirements\&.urls\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
