.TH "identifier" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
identifier
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClingoApp\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBparser\fP = argparse\&.ArgumentParser(description='Input class json')"
.br
.ti -1c
.RI "\fBtype\fP"
.br
.ti -1c
.RI "\fBstr\fP"
.br
.ti -1c
.RI "\fBdefault\fP"
.br
.ti -1c
.RI "\fBhelp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "identifier\&.default"

.PP
Definition at line \fB9\fP of file \fBidentifier\&.py\fP\&.
.SS "identifier\&.help"

.PP
Definition at line \fB9\fP of file \fBidentifier\&.py\fP\&.
.SS "identifier\&.parser = argparse\&.ArgumentParser(description='Input class json')"

.PP
Definition at line \fB5\fP of file \fBidentifier\&.py\fP\&.
.SS "identifier\&.str"

.PP
Definition at line \fB9\fP of file \fBidentifier\&.py\fP\&.
.SS "identifier\&.type"

.PP
Definition at line \fB9\fP of file \fBidentifier\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
