.TH "scheduleFunctions/models.py" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions/models.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Room\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Day\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Course\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Schedule\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Section\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.PlanSemester\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Change\fP"
.br
.ti -1c
.RI "class \fBscheduleFunctions\&.models\&.Conflict\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscheduleFunctions\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.models\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBscheduleFunctions\&.models\&.FALL\fP = 'F'"
.br
.ti -1c
.RI "str \fBscheduleFunctions\&.models\&.SPRING\fP = 'S'"
.br
.ti -1c
.RI "dict \fBscheduleFunctions\&.models\&.SEMESTER_CHOICES\fP"
.br
.ti -1c
.RI "str \fBscheduleFunctions\&.models\&.FRESHMAN\fP = 'FR'"
.br
.ti -1c
.RI "str \fBscheduleFunctions\&.models\&.SOPHOMORE\fP = 'SO'"
.br
.ti -1c
.RI "str \fBscheduleFunctions\&.models\&.JUNIOR\fP = 'JR'"
.br
.ti -1c
.RI "str \fBscheduleFunctions\&.models\&.SENIOR\fP = 'SR'"
.br
.ti -1c
.RI "str \fBscheduleFunctions\&.models\&.GRADUATE\fP = 'GR'"
.br
.ti -1c
.RI "dict \fBscheduleFunctions\&.models\&.YEAR_IN_SCHOOL_CHOICES\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
