.TH "myproject.urls" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myproject.urls
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBurlpatterns\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
URL configuration for myproject project\&.

The `urlpatterns` list routes URLs to views\&. For more information please see:
    https://docs\&.djangoproject\&.com/en/5\&.1/topics/http/urls/
Examples:
Function views
    1\&. Add an import:  from my_app import views
    2\&. Add a URL to urlpatterns:  path('', views\&.home, name='home')
Class-based views
    1\&. Add an import:  from other_app\&.views import Home
    2\&. Add a URL to urlpatterns:  path('', Home\&.as_view(), name='home')
Including another URLconf
    1\&. Import the include() function: from django\&.urls import include, path
    2\&. Add a URL to urlpatterns:  path('blog/', include('blog\&.urls'))

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "list myproject\&.urls\&.urlpatterns"
\fBInitial value:\fP
.nf
1 =  [
2     path('admin/doc/', include('django\&.contrib\&.admindocs\&.urls')),
3     path('admin/', admin\&.site\&.urls),
4     path('run\-script/', run_script, name='run_script'),
5     path('dashboard/', dashboard_view, name='dashboard'),
6     path('schedule/', schedule_view, name='schedule'),
7     path('', login, name='home'),  # Add homepage route
8 ]
.PP
.fi

.PP
Definition at line \fB21\fP of file \fBurls\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
