.TH "myproject" 3 "Version 3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myproject
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBasgi\fP"
.br
.ti -1c
.RI "namespace \fBsettings\fP"
.br
.ti -1c
.RI "namespace \fBurls\fP"
.br
.ti -1c
.RI "namespace \fBwsgi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
