.TH "processor.py" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
processor.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBprocessor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBprocessor\&.get_cist_csci_courses\fP (json_file_path)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBprocessor\&.json_file\fP = 'fa21\-fa24\&.json'"
.br
.ti -1c
.RI "\fBprocessor\&.result\fP = \fBget_cist_csci_courses\fP(\fBjson_file\fP)"
.br
.ti -1c
.RI "\fBprocessor\&.encoding\fP"
.br
.ti -1c
.RI "\fBprocessor\&.out\fP"
.br
.ti -1c
.RI "\fBprocessor\&.indent\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
