.TH "processor" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
processor
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBget_cist_csci_courses\fP (json_file_path)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBjson_file\fP = 'fa21\-fa24\&.json'"
.br
.ti -1c
.RI "\fBresult\fP = \fBget_cist_csci_courses\fP(\fBjson_file\fP)"
.br
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBout\fP"
.br
.ti -1c
.RI "\fBindent\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "processor\&.get_cist_csci_courses ( json_file_path)"

.PP
Definition at line \fB3\fP of file \fBprocessor\&.py\fP\&.
.nf
3 def get_cist_csci_courses(json_file_path):
4     with open(json_file_path, 'r', encoding='utf\-8') as f:
5         data = json\&.load(f)
6 
7     subjects_of_interest = {"CIST", "CSCI"}
8     filtered_courses = {}
9 
10     for term, subjects_dict in data\&.items():
11         for subject_code, courses_dict in subjects_dict\&.items():
12             if subject_code in subjects_of_interest:
13                 if term not in filtered_courses:
14                     filtered_courses[term] = {}
15                 filtered_courses[term][subject_code] = courses_dict
16 
17     return filtered_courses
.PP
.fi

.SH "Variable Documentation"
.PP 
.SS "processor\&.encoding"

.PP
Definition at line \fB21\fP of file \fBprocessor\&.py\fP\&.
.SS "processor\&.indent"

.PP
Definition at line \fB22\fP of file \fBprocessor\&.py\fP\&.
.SS "str processor\&.json_file = 'fa21\-fa24\&.json'"

.PP
Definition at line \fB19\fP of file \fBprocessor\&.py\fP\&.
.SS "processor\&.out"

.PP
Definition at line \fB22\fP of file \fBprocessor\&.py\fP\&.
.SS "processor\&.result = \fBget_cist_csci_courses\fP(\fBjson_file\fP)"

.PP
Definition at line \fB20\fP of file \fBprocessor\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
