.TH "scheduleFunctions.tests.ScriptViewTests" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.tests.ScriptViewTests
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestScriptRun_converter\fP (self)"
.br
.ti -1c
.RI "\fBtestScriptRun_identifier\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBtests\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "scheduleFunctions\&.tests\&.ScriptViewTests\&.testScriptRun_converter ( self)"

.PP
Definition at line \fB49\fP of file \fBtests\&.py\fP\&.
.nf
49     def testScriptRun_converter(self):
50         form_data = {
51             'script': 'converter',
52             # \&.\&.\&. other fields
53         }
54         response = self\&.client\&.get(reverse(run_script_name), form_data)
55         self\&.assertEqual(response\&.status_code, 200)
56         \&.\&.\&.
57         
.PP
.fi

.SS "scheduleFunctions\&.tests\&.ScriptViewTests\&.testScriptRun_identifier ( self)"

.PP
Definition at line \fB58\fP of file \fBtests\&.py\fP\&.
.nf
58     def testScriptRun_identifier(self):
59         form_data = {
60             'script': 'identifier',
61             # \&.\&.\&. other fields
62         }
63         response = self\&.client\&.get(reverse(run_script_name), form_data)
64         self\&.assertEqual(response\&.status_code, 200)
65         \&.\&.\&.
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
