.TH "scheduleFunctions.models" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChange\fP"
.br
.ti -1c
.RI "class \fBConflict\fP"
.br
.ti -1c
.RI "class \fBCourse\fP"
.br
.ti -1c
.RI "class \fBDay\fP"
.br
.ti -1c
.RI "class \fBPlanSemester\fP"
.br
.ti -1c
.RI "class \fBRoom\fP"
.br
.ti -1c
.RI "class \fBSchedule\fP"
.br
.ti -1c
.RI "class \fBSection\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBFALL\fP = 'F'"
.br
.ti -1c
.RI "str \fBSPRING\fP = 'S'"
.br
.ti -1c
.RI "dict \fBSEMESTER_CHOICES\fP"
.br
.ti -1c
.RI "str \fBFRESHMAN\fP = 'FR'"
.br
.ti -1c
.RI "str \fBSOPHOMORE\fP = 'SO'"
.br
.ti -1c
.RI "str \fBJUNIOR\fP = 'JR'"
.br
.ti -1c
.RI "str \fBSENIOR\fP = 'SR'"
.br
.ti -1c
.RI "str \fBGRADUATE\fP = 'GR'"
.br
.ti -1c
.RI "dict \fBYEAR_IN_SCHOOL_CHOICES\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "str scheduleFunctions\&.models\&.FALL = 'F'"

.PP
Definition at line \fB4\fP of file \fBmodels\&.py\fP\&.
.SS "str scheduleFunctions\&.models\&.FRESHMAN = 'FR'"

.PP
Definition at line \fB11\fP of file \fBmodels\&.py\fP\&.
.SS "str scheduleFunctions\&.models\&.GRADUATE = 'GR'"

.PP
Definition at line \fB15\fP of file \fBmodels\&.py\fP\&.
.SS "str scheduleFunctions\&.models\&.JUNIOR = 'JR'"

.PP
Definition at line \fB13\fP of file \fBmodels\&.py\fP\&.
.SS "dict scheduleFunctions\&.models\&.SEMESTER_CHOICES"
\fBInitial value:\fP
.nf
1 =  {
2     FALL: "Fall",
3     SPRING: "Spring"
4 }
.PP
.fi

.PP
Definition at line \fB6\fP of file \fBmodels\&.py\fP\&.
.SS "str scheduleFunctions\&.models\&.SENIOR = 'SR'"

.PP
Definition at line \fB14\fP of file \fBmodels\&.py\fP\&.
.SS "str scheduleFunctions\&.models\&.SOPHOMORE = 'SO'"

.PP
Definition at line \fB12\fP of file \fBmodels\&.py\fP\&.
.SS "str scheduleFunctions\&.models\&.SPRING = 'S'"

.PP
Definition at line \fB5\fP of file \fBmodels\&.py\fP\&.
.SS "dict scheduleFunctions\&.models\&.YEAR_IN_SCHOOL_CHOICES"
\fBInitial value:\fP
.nf
1 =  {
2     FRESHMAN: "Freshman",
3     SOPHOMORE: "Sophomore",
4     JUNIOR: "Junior",
5     SENIOR: "Senior",
6     GRADUATE: "Graduate",
7 }
.PP
.fi

.PP
Definition at line \fB16\fP of file \fBmodels\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
