.TH "scheduleFunctions.models.Course" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.models.Course
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBsubject\fP = models\&.CharField(max_length=5)"
.br
.ti -1c
.RI "\fBclassNumber\fP = models\&.IntegerField()"
.br
.ti -1c
.RI "\fBprerequisites\fP = models\&.ManyToManyField('self')"
.br
.ti -1c
.RI "\fBequivalent_courses\fP = models\&.ManyToManyField('self')"
.br
.ti -1c
.RI "\fBsame_semester_courses\fP = models\&.ManyToManyField('self')"
.br
.ti -1c
.RI "\fBcredits\fP = models\&.IntegerField()"
.br
.ti -1c
.RI "\fBweight\fP = models\&.IntegerField()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "scheduleFunctions\&.models\&.Course\&.classNumber = models\&.IntegerField()\fR [static]\fP"

.PP
Definition at line \fB50\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Course\&.credits = models\&.IntegerField()\fR [static]\fP"

.PP
Definition at line \fB54\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Course\&.equivalent_courses = models\&.ManyToManyField('self')\fR [static]\fP"

.PP
Definition at line \fB52\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Course\&.prerequisites = models\&.ManyToManyField('self')\fR [static]\fP"

.PP
Definition at line \fB51\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Course\&.same_semester_courses = models\&.ManyToManyField('self')\fR [static]\fP"

.PP
Definition at line \fB53\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Course\&.subject = models\&.CharField(max_length=5)\fR [static]\fP"

.PP
Definition at line \fB49\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Course\&.weight = models\&.IntegerField()\fR [static]\fP"

.PP
Definition at line \fB55\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
