.TH "scheduleFunctions.models.Room" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.models.Room
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBbuilding\fP = models\&.CharField(max_length=5)"
.br
.ti -1c
.RI "\fBroom_number\fP = models\&.IntegerField()"
.br
.ti -1c
.RI "\fBcapacity\fP = models\&.IntegerField()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB24\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "scheduleFunctions\&.models\&.Room\&.building = models\&.CharField(max_length=5)\fR [static]\fP"

.PP
Definition at line \fB25\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Room\&.capacity = models\&.IntegerField()\fR [static]\fP"

.PP
Definition at line \fB27\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Room\&.room_number = models\&.IntegerField()\fR [static]\fP"

.PP
Definition at line \fB26\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
