.TH "scheduleFunctions.models.Section" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.models.Section
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBcourse\fP = models\&.ForeignKey(\fBCourse\fP, on_delete = models\&.CASCADE)"
.br
.ti -1c
.RI "\fBsection_id\fP = models\&.IntegerField()"
.br
.ti -1c
.RI "\fBprofessor\fP = models\&.CharField(max_length=255)"
.br
.ti -1c
.RI "\fBstart_time\fP = models\&.IntegerField()"
.br
.ti -1c
.RI "\fBend_time\fP = models\&.IntegerField()"
.br
.ti -1c
.RI "\fBdays\fP = models\&.ManyToManyField(\fBDay\fP)"
.br
.ti -1c
.RI "\fBroom\fP = models\&.ForeignKey(\fBRoom\fP, on_delete = models\&.SET_NULL)"
.br
.ti -1c
.RI "\fBschdule\fP = models\&.ForeignKey(\fBSchedule\fP, on_delete = models\&.CASCADE)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB71\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "scheduleFunctions\&.models\&.Section\&.course = models\&.ForeignKey(\fBCourse\fP, on_delete = models\&.CASCADE)\fR [static]\fP"

.PP
Definition at line \fB72\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Section\&.days = models\&.ManyToManyField(\fBDay\fP)\fR [static]\fP"

.PP
Definition at line \fB77\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Section\&.end_time = models\&.IntegerField()\fR [static]\fP"

.PP
Definition at line \fB76\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Section\&.professor = models\&.CharField(max_length=255)\fR [static]\fP"

.PP
Definition at line \fB74\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Section\&.room = models\&.ForeignKey(\fBRoom\fP, on_delete = models\&.SET_NULL)\fR [static]\fP"

.PP
Definition at line \fB78\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Section\&.schdule = models\&.ForeignKey(\fBSchedule\fP, on_delete = models\&.CASCADE)\fR [static]\fP"

.PP
Definition at line \fB79\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Section\&.section_id = models\&.IntegerField()\fR [static]\fP"

.PP
Definition at line \fB73\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Section\&.start_time = models\&.IntegerField()\fR [static]\fP"

.PP
Definition at line \fB75\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
