.TH "scheduleFunctions.models.Schedule" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.models.Schedule
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fByear\fP"
.br
.ti -1c
.RI "\fBsemester\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB58\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "scheduleFunctions\&.models\&.Schedule\&.semester\fR [static]\fP"
\fBInitial value:\fP
.nf
=  models\&.CharField(
        max_length=1,
        choices=SEMESTER_CHOICES,
        default=FALL,
    )
.PP
.fi

.PP
Definition at line \fB64\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Schedule\&.year\fR [static]\fP"
\fBInitial value:\fP
.nf
=  models\&.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=FRESHMAN,
    )
.PP
.fi

.PP
Definition at line \fB59\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
