.TH "scheduleFunctions.models.Conflict" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.models.Conflict
.SH SYNOPSIS
.br
.PP
.PP
Inherits models\&.Model\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBsectionA\fP = models\&.ForeignKey(\fBSection\fP, on_delete = models\&.CASCADE)"
.br
.ti -1c
.RI "\fBsectionB\fP = models\&.ForeignKey(\fBSection\fP, on_delete = models\&.CASCADE)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB103\fP of file \fBmodels\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "scheduleFunctions\&.models\&.Conflict\&.sectionA = models\&.ForeignKey(\fBSection\fP, on_delete = models\&.CASCADE)\fR [static]\fP"

.PP
Definition at line \fB104\fP of file \fBmodels\&.py\fP\&.
.SS "scheduleFunctions\&.models\&.Conflict\&.sectionB = models\&.ForeignKey(\fBSection\fP, on_delete = models\&.CASCADE)\fR [static]\fP"

.PP
Definition at line \fB105\fP of file \fBmodels\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
