.TH "scheduleFunctions.tests" 3 "Version 3" "ASP Schedule Optimizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions.tests
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDashboardViewTests\fP"
.br
.ti -1c
.RI "class \fBLoginViewTests\fP"
.br
.ti -1c
.RI "class \fBScriptViewTests\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBlogin_name\fP = 'home'"
.br
.ti -1c
.RI "str \fBdashboard_name\fP = 'dashboard'"
.br
.ti -1c
.RI "str \fBrun_script_name\fP = 'run_script'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "str scheduleFunctions\&.tests\&.dashboard_name = 'dashboard'"

.PP
Definition at line \fB5\fP of file \fBtests\&.py\fP\&.
.SS "str scheduleFunctions\&.tests\&.login_name = 'home'"

.PP
Definition at line \fB4\fP of file \fBtests\&.py\fP\&.
.SS "str scheduleFunctions\&.tests\&.run_script_name = 'run_script'"

.PP
Definition at line \fB6\fP of file \fBtests\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ASP Schedule Optimizer from the source code\&.
