.TH "scheduleFunctions/views.py" 3 "Version 3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduleFunctions/views.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBscheduleFunctions\fP"
.br
.ti -1c
.RI "namespace \fBscheduleFunctions\&.views\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.login\fP (request)"
.br
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.dashboard_view\fP (request)"
.br
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.schedule_view\fP (request)"
.br
.ti -1c
.RI "\fBscheduleFunctions\&.views\&.run_script\fP (request)"
.br
.ti -1c
.RI "dict \fBscheduleFunctions\&.views\&.get_section_details\fP (str course, int section)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBscheduleFunctions\&.views\&.example_course_list\fP"
.br
.ti -1c
.RI "list \fBscheduleFunctions\&.views\&.example_conflict_list\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
